version: 2
updates:
  # Keep Dart dependencies up to date (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(pub)"
      include: "scope"
    assignees:
      - KristijanMitrik
      - dmacan23

 # Keep Android dependencies up to date (build.gradle)     
  - package-ecosystem: gradle
    directory: "android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(android)"
    assignees:
      - KristijanMitrik
      - dmacan23

  # Keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    assignees:
      - KristijanMitrik
      - dmacan23
