version: 2
updates:
  # Keep Dart dependencies up to date (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(pub)"
      include: "scope"
    reviewers:
      - KristijanMitrik
      - dmacan23
  - package-ecosystem: gradle
    directory: "android"
    schedule:
      interval: "weekly"   
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(android)"    
    reviewers:
      - KristijanMitrik
      - dmacan23   
    registries:
      - github-dependencies  

  # Keep GitHub Actions workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    reviewers:
      - KristijanMitrik
      - dmacan23  

registries:
  github-dependencies:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.VPNAPI_GITHUB_PAT }}
