name: mysterium_vpn
description: Next-gen Mysterium VPN client for mobile (iOS/Android) and desktop (Windows/MacOS/Linux).

publish_to: "none"
version: 2.4.6-dev

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: 3.41.9

dependencies:
  app_links: 7.0.0
  app_settings: 7.0.0
  auto_size_text: 3.0.0
  beamer: 1.7.0
  circle_flags: 5.0.1
  clipboard:
    git:
      url: https://github.com/samuelezedi/flutter_clipboard.git
      ref: 6f8dce7b71396b713ab3d71cb20a04967c5458fd
  collection: 1.19.1
  configcat_client: 4.1.1
  connectivity_plus: 6.1.5
  crypto: 3.0.7
  device_info_plus: 13.1.0
  dio: 5.9.2
  easy_localization: 3.0.8
  easy_localization_loader: 2.0.2
  firebase_analytics: 12.4.0
  firebase_core: 4.8.0
  firebase_crashlytics: 5.2.1
  firebase_performance: 0.11.4
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.3+1
  flutter_launcher_icons: 0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_map: 8.3.0
  flutter_mobx: 2.3.0
  flutter_native_splash: 2.4.7
  flutter_portal: 1.1.4
  flutter_secure_storage:
    git:
      url: https://github.com/KristijanMitrik/flutter_secure_storage.git
      path: flutter_secure_storage
      ref: 9.2.6
  flutter_svg: 2.2.4
  flutter_udid: 4.1.2
  freezed_annotation: 3.1.0
  google_fonts: 8.0.2
  google_sign_in: 7.2.0
  hive_ce: 2.19.3
  hive_ce_flutter: 2.3.4
  hooks_riverpod: 3.3.1
  in_app_purchase: 3.2.3
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: 0.4.5
  in_app_review: 2.0.11
  in_app_update: 4.2.5
  intl: 0.20.2
  json_annotation: 4.11.0
  latlong2: 0.9.1
  mail_launcher:
    path: ./packages/mail_launcher
  mobx: 2.6.0
  modal_bottom_sheet: 3.0.0
  money2: 6.3.0
  mqtt5_client: 4.17.0
  mysterium_vpn_design:
    path: ../mysterium-vpn-design
    # git:
    #   url: https://github.com/mysteriumnetwork/mysterium-vpn-design.git
    #   ref: 0.0.17
  onesignal_flutter: 5.5.3
  open_store: 0.5.0
  openvpn_dart:
    git:
      url: https://github.com/mysteriumnetwork/openvpn_dart.git
      ref: extract-driver
  package_info_plus: 10.1.0
  reactive_forms: 17.0.1
  retry: ^3.1.2
  sentry_flutter: 9.19.0
  shared_preferences: 2.5.5
  shimmer: 3.0.0
  showcaseview: 5.0.2
  sign_in_with_apple: 8.0.0
  sliver_tools: ^0.2.12
  stack_trace: 1.12.1
  store_checker_windows:
    path: ./packages/store_checker_windows
  styled_widget: 0.4.1
  talker: 5.1.17
  talker_dio_logger: 5.1.17
  tray_manager: 0.5.2
  url_launcher: 6.3.2
  url_protocol:
    git:
      url: https://github.com/KristijanMitrik/flutter_url_protocol
      ref: main
  vpn_api:
    git:
      url: https://github.com/mysteriumnetwork/mysterium-vpn-api-client-dart.git
      ref: 1.0.66
  webview_flutter: 4.13.1
  window_manager: 0.5.1
  wireguard_dart:
    git:
      url: https://github.com/mysteriumnetwork/wireguard_dart.git
      ref: 0.9.11

dev_dependencies:
  build_runner: 2.13.0
  cider: 0.2.10
  easy_localization_sheet: ^1.1.0
  flutter_gen_runner: 5.13.0+1
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.5
  hive_ce_generator: 1.11.0
  integration_test:
    sdk: flutter
  json_serializable: 6.13.0
  mobx_codegen: 2.7.6
  mockito: 5.6.3
  msix: 3.16.13
  patrol: 4.3.0

dependency_overrides:
  flutter_secure_storage_windows:
    git:
      url: https://github.com/KristijanMitrik/flutter_secure_storage.git
      path: flutter_secure_storage_windows
      ref: 9.2.6

msix_config:
  display_name: Mysterium VPN
  publisher_display_name: UAB MN Technologijos
  logo_path: assets/logo/prod/desktop.png
  language: en-us
  capabilities: runFullTrust, allowElevation, internetClient
  protocol_activation: mysteriumvpn
  override_executable: mysterium_vpn.exe

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/logo/dev/
    - assets/logo/prod/
    - assets/icons/
    - assets/images/
    - resources/langs/
    - assets/google_fonts/
    - assets/data/
      # BEGIN auto-generated assets
    - assets/map_tiles/light/
    - assets/map_tiles/light/4/
    - assets/map_tiles/light/4/9/
    - assets/map_tiles/light/4/0/
    - assets/map_tiles/light/4/11/
    - assets/map_tiles/light/4/7/
    - assets/map_tiles/light/4/6/
    - assets/map_tiles/light/4/1/
    - assets/map_tiles/light/4/10/
    - assets/map_tiles/light/4/8/
    - assets/map_tiles/light/4/4/
    - assets/map_tiles/light/4/15/
    - assets/map_tiles/light/4/3/
    - assets/map_tiles/light/4/12/
    - assets/map_tiles/light/4/2/
    - assets/map_tiles/light/4/13/
    - assets/map_tiles/light/4/5/
    - assets/map_tiles/light/4/14/
    - assets/map_tiles/light/3/
    - assets/map_tiles/light/3/0/
    - assets/map_tiles/light/3/7/
    - assets/map_tiles/light/3/6/
    - assets/map_tiles/light/3/1/
    - assets/map_tiles/light/3/4/
    - assets/map_tiles/light/3/3/
    - assets/map_tiles/light/3/2/
    - assets/map_tiles/light/3/5/
    - assets/map_tiles/dark/
    - assets/map_tiles/dark/4/
    - assets/map_tiles/dark/4/9/
    - assets/map_tiles/dark/4/0/
    - assets/map_tiles/dark/4/11/
    - assets/map_tiles/dark/4/7/
    - assets/map_tiles/dark/4/6/
    - assets/map_tiles/dark/4/1/
    - assets/map_tiles/dark/4/10/
    - assets/map_tiles/dark/4/8/
    - assets/map_tiles/dark/4/4/
    - assets/map_tiles/dark/4/15/
    - assets/map_tiles/dark/4/3/
    - assets/map_tiles/dark/4/12/
    - assets/map_tiles/dark/4/2/
    - assets/map_tiles/dark/4/13/
    - assets/map_tiles/dark/4/5/
    - assets/map_tiles/dark/4/14/
    - assets/map_tiles/dark/3/
    - assets/map_tiles/dark/3/0/
    - assets/map_tiles/dark/3/7/
    - assets/map_tiles/dark/3/6/
    - assets/map_tiles/dark/3/1/
    - assets/map_tiles/dark/3/4/
    - assets/map_tiles/dark/3/3/
    - assets/map_tiles/dark/3/2/
    - assets/map_tiles/dark/3/5/
    # END auto-generated assets

patrol:
  app_name: Mysterium VPN
  android:
    package_name: com.mysteriumvpn.android.test
  ios:
    bundle_id: com.mysteriumvpn.test
  macos:
    bundle_id: com.mysteriumvpn.test

easy_localization_sheet:
  csv_url: "https://docs.google.com/spreadsheets/d/1_rcGKCSnaBzF-dHnow53aBxBu_av_jhLS-x0HGeY5tE/export?format=csv&gid=216784309"
  output_dir: "resources/langs" # Optional, default is assets
