name: mysterium_vpn
description: Next-gen Mysterium VPN client for mobile (iOS/Android) and desktop (Windows/MacOS/Linux).

publish_to: 'none'
version: 1.5.0+55

environment:
  sdk: '^3.0.0'
  flutter: ">=3.7.0"

dependencies:
  app_links: ^3.4.5
  appsflyer_sdk: ^6.12.2
  async: ^2.11.0
  auto_size_text: ^3.0.0
  beamer: ^1.5.6
  circle_flags: ^3.0.1
  clipboard: ^0.1.3
  collection: ^1.17.2
  connectivity_plus: ^5.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  easy_localization: ^3.0.3
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_performance: ^0.9.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.1.1
  flutter_native_splash: ^2.2.17
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.8
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.5
  import_sorter: ^4.6.0
  in_app_purchase: ^3.1.11
  in_app_purchase_storekit: ^0.3.7
  in_app_review: ^2.0.8
  intercom_flutter: ^8.0.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  mobx: ^2.2.1
  modal_bottom_sheet: ^3.0.0-pre
  open_mail_app: ^0.4.5
  package_info_plus: ^4.2.0
  reactive_forms: ^15.0.0
  sentry_dio: ^7.11.0
  sentry_flutter: ^7.11.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  stack_trace: ^1.11.0
  styled_widget: ^0.4.1
  tray_manager: ^0.2.0
  url_launcher: ^6.2.1
  url_protocol:
    git:
      url: https://github.com/KristijanMitrik/flutter_url_protocol
      ref: main
  window_manager: ^0.3.5
  wireguard_dart:
    git:
      url: https://github.com/mysteriumnetwork/wireguard_dart.git
      ref: 0.4.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.0
  mobx_codegen: ^2.1.1
  msix: ^3.15.1

msix_config:
  display_name: Mysterium VPN Test
  publisher_display_name: UAB MN Technologijos
  logo_path: assets/logo/dev/desktop.png
  identity_name: UABMNTechnologijos.MysteriumVPNTest
  publisher: CN=B6C98289-B62E-4315-9F65-9B59DB0FC5AC
  output_name: MysteriumVPNTest
  language: en-us
  windows_build_args: --dart-define FLAVOR=DEV
  store: true
  capabilities: runFullTrust, allowElevation, internetClient
  protocol_activation: mysteriumvpn

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/logo/dev/
    - assets/logo/prod/
    - assets/icons/
    - assets/images/
    - assets/flags/
    - assets/animations/
    - resources/langs/
