allprojects {
    repositories {
        google()
        mavenCentral()
    }
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group
                    }
                    if (project.android.compileSdkVersion != null &&
                        project.android.compileSdkVersion.toString().contains("33")) {
                        compileSdk = 36
                    }
                }
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    configurations.configureEach {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.google.android.gms' &&
                    details.requested.name == 'play-services-basement') {
                details.useVersion '18.6.0'
                details.because 'Force usage of play-services-basement version 18.6.0 due to CVE fix'
            }
            if (details.requested.group == 'com.google.firebase' &&
                    details.requested.name == 'firebase-measurement-connector') {
                details.useVersion '20.0.1'
                details.because 'Force firebase-measurement-connector to 20.0.1 for consistency and CVE fix'
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
