// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmRjjve4OlKZ4UBx9vGAzOwfkEbQw4j8',
    appId: '1:104590535697:android:6b5e69696fcf98abf355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpAxPxcYK5BfP_9z2aT2-avOI3qZ5Py0',
    appId: '1:104590535697:ios:caac04df7c37b40af355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
    iosClientId: '104590535697-321dcucindetpslpqcgjl3t0j6d68sf1.apps.googleusercontent.com',
    iosBundleId: 'com.mysterium.vpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfpAxPxcYK5BfP_9z2aT2-avOI3qZ5Py0',
    appId: '1:104590535697:ios:ce4c86a428e9e135f355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
    iosClientId: '104590535697-24pmcrndecf8jk6n9hmkgucb701f9l81.apps.googleusercontent.com',
    iosBundleId: 'com.mysterium.mysteriumVpn',
  );
}
