// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWAD1DgEGtBxYtCcZ-WCfkk6iDL7KniA4',
    appId: '1:139303438361:android:83ba42de41fde6f3b7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Z7KPJJDOEFgIeGue8IFZdBkmq_6cv4U',
    appId: '1:139303438361:ios:cc0a667a11731afab7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
    iosClientId: '139303438361-h8a0q4erpab3aov2dunb8bsne6bf52r3.apps.googleusercontent.com',
    iosBundleId: 'com.mysterium.vpn.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Z7KPJJDOEFgIeGue8IFZdBkmq_6cv4U',
    appId: '1:139303438361:ios:cc0a667a11731afab7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
    iosClientId: '139303438361-h8a0q4erpab3aov2dunb8bsne6bf52r3.apps.googleusercontent.com',
    iosBundleId: 'com.mysterium.vpn.dev',
  );
}
