// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mysterium_vpn/models/user_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ApprovalAdapter());
    registerAdapter(UserDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ApprovalAdapter());
    registerAdapter(UserDataAdapter());
  }
}
