import 'dart:convert';
import 'dart:io';

/// Standalone generator for `lib/l10n/tr_bridge_keys.g.dart` — the fast path
/// (`make localizely-generate`, no build_runner). The build_runner builder in
/// `tr_bridge_builder.dart` shares [renderTrBridge], and the drift-guard test
/// checks the checked-in file against it.
Future<void> main() async {
  const output = 'lib/l10n/tr_bridge_keys.g.dart';
  final arb = jsonDecode(await File('lib/l10n/intl_en.arb').readAsString()) as Map<String, dynamic>;
  await File(output).writeAsString(renderTrBridge(arb));
  stdout.writeln('wrote $output');
}

/// Renders the bridge source from a decoded ARB map: every no-argument key (not
/// `@`-metadata, no `{...}` placeholder) mapped to its generated `S` getter.
/// Keys with placeholders are `S` methods and are called directly.
String renderTrBridge(Map<String, dynamic> arb) {
  final keys =
      arb.keys
          .where((k) => !k.startsWith('@'))
          .where((k) => !arb[k].toString().contains('{'))
          .toList()
        ..sort();

  final b = StringBuffer()
    ..writeln('// GENERATED by tr_bridge_generator — do not edit.')
    ..writeln("import 'package:mysterium_vpn/generated/l10n.dart';")
    ..writeln()
    ..writeln('/// Runtime key -> no-arg S getter, for dynamic `Tr.byKey` lookups.')
    ..writeln('final Map<String, String Function(S)> kTrBridge = {');
  for (final k in keys) {
    b.writeln("  '$k': (s) => s.$k,");
  }
  b.writeln('};');
  return b.toString();
}
