import 'dart:convert';

import 'package:build/build.dart';

/// build_runner factory (registered in build.yaml).
Builder trBridgeBuilder(BuilderOptions options) => _TrBridgeBuilder();

/// Generates `lib/l10n/tr_bridge_keys.g.dart` from `lib/l10n/intl_en.arb`: a map
/// from each no-argument translation key to its generated `S` getter, powering
/// dynamic `Tr.byKey` lookups (Dart has no reflection). Keys whose value has a
/// `{...}` placeholder are `S` methods and are excluded (called directly).
class _TrBridgeBuilder implements Builder {
  static const _output = 'lib/l10n/tr_bridge_keys.g.dart';

  @override
  Map<String, List<String>> get buildExtensions => const {
    '^lib/l10n/intl_en.arb': [_output],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final arb = jsonDecode(await buildStep.readAsString(buildStep.inputId)) as Map<String, dynamic>;
    final source = renderTrBridge(arb);
    await buildStep.writeAsString(AssetId(buildStep.inputId.package, _output), source);
  }
}

/// Pure render of the bridge source from a decoded ARB map. Shared with the
/// drift-guard test so it can re-derive the expected keys without duplicating
/// the filter rules.
String renderTrBridge(Map<String, dynamic> arb) {
  final keys =
      arb.keys
          .where((k) => !k.startsWith('@'))
          .where((k) => !arb[k].toString().contains('{'))
          .toList()
        ..sort();

  final b = StringBuffer()
    ..writeln('// GENERATED by tr_bridge_builder — do not edit.')
    ..writeln("import 'package:mysterium_vpn/generated/l10n.dart';")
    ..writeln()
    ..writeln('/// Runtime key -> no-arg S getter, for dynamic `Tr.byKey` lookups.')
    ..writeln('final Map<String, String Function(S)> kTrBridge = {');
  for (final k in keys) {
    b.writeln("  '$k': (s) => s.$k,");
  }
  b.writeln('};');
  return b.toString();
}
