// Mocks generated by Mockito 5.4.4 from annotations
// in mysterium_vpn/test/stores/banners_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:in_app_purchase/in_app_purchase.dart' as _i15;
import 'package:mobx/mobx.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:mysterium_vpn/common/enums/banner_type.dart' as _i11;
import 'package:mysterium_vpn/common/enums/enums.dart' as _i14;
import 'package:mysterium_vpn/models/ip_info.dart' as _i9;
import 'package:mysterium_vpn/models/location.dart' as _i2;
import 'package:mysterium_vpn/models/purchasable_product.dart' as _i4;
import 'package:mysterium_vpn/models/report_broken_node_request.dart' as _i10;
import 'package:mysterium_vpn/models/subscription.dart' as _i13;
import 'package:mysterium_vpn/models/user_data.dart' as _i8;
import 'package:mysterium_vpn/services/api/api_service.dart' as _i6;
import 'package:mysterium_vpn/stores/remote_config/remote_config_store.dart' as _i16;
import 'package:mysterium_vpn/stores/subscription_store.dart' as _i12;
import 'package:vpn_api/vpn_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPNLocations_0 extends _i1.SmartFake implements _i2.VPNLocations {
  _FakeVPNLocations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWireguardConnectResponse_1 extends _i1.SmartFake
    implements _i3.WireguardConnectResponse {
  _FakeWireguardConnectResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePurchasableProduct_2 extends _i1.SmartFake implements _i4.PurchasableProduct {
  _FakePurchasableProduct_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_3 extends _i1.SmartFake implements _i5.ReactiveContext {
  _FakeReactiveContext_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObservableList_4<T> extends _i1.SmartFake implements _i5.ObservableList<T> {
  _FakeObservableList_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObservableFuture_5<T> extends _i1.SmartFake implements _i5.ObservableFuture<T> {
  _FakeObservableFuture_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  @override
  _i7.Future<void> setNotificationsApproval({required bool? approval}) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationsApproval,
          [],
          {#approval: approval},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.Approval> getNotificationsApproval() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationsApproval,
          [],
        ),
        returnValue: _i7.Future<_i8.Approval>.value(_i8.Approval.approved),
        returnValueForMissingStub: _i7.Future<_i8.Approval>.value(_i8.Approval.approved),
      ) as _i7.Future<_i8.Approval>);

  @override
  _i7.Future<_i2.VPNLocations> fetchVPNLocations({required String? keyword}) => (super.noSuchMethod(
        Invocation.method(
          #fetchVPNLocations,
          [],
          {#keyword: keyword},
        ),
        returnValue: _i7.Future<_i2.VPNLocations>.value(_FakeVPNLocations_0(
          this,
          Invocation.method(
            #fetchVPNLocations,
            [],
            {#keyword: keyword},
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i2.VPNLocations>.value(_FakeVPNLocations_0(
          this,
          Invocation.method(
            #fetchVPNLocations,
            [],
            {#keyword: keyword},
          ),
        )),
      ) as _i7.Future<_i2.VPNLocations>);

  @override
  _i7.Future<void> addRecentLocation(_i2.VPNLocation? location) => (super.noSuchMethod(
        Invocation.method(
          #addRecentLocation,
          [location],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.VPNLocation>> getRecentLocations({required String? keyword}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLocations,
          [],
          {#keyword: keyword},
        ),
        returnValue: _i7.Future<List<_i2.VPNLocation>>.value(<_i2.VPNLocation>[]),
        returnValueForMissingStub: _i7.Future<List<_i2.VPNLocation>>.value(<_i2.VPNLocation>[]),
      ) as _i7.Future<List<_i2.VPNLocation>>);

  @override
  _i7.Future<_i3.WireguardConnectResponse> fetchVpnConfig(
          {required _i3.WireguardConnectRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVpnConfig,
          [],
          {#request: request},
        ),
        returnValue: _i7.Future<_i3.WireguardConnectResponse>.value(_FakeWireguardConnectResponse_1(
          this,
          Invocation.method(
            #fetchVpnConfig,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.WireguardConnectResponse>.value(_FakeWireguardConnectResponse_1(
          this,
          Invocation.method(
            #fetchVpnConfig,
            [],
            {#request: request},
          ),
        )),
      ) as _i7.Future<_i3.WireguardConnectResponse>);

  @override
  _i7.Future<_i9.IPInfo?> getIPAdress() => (super.noSuchMethod(
        Invocation.method(
          #getIPAdress,
          [],
        ),
        returnValue: _i7.Future<_i9.IPInfo?>.value(),
        returnValueForMissingStub: _i7.Future<_i9.IPInfo?>.value(),
      ) as _i7.Future<_i9.IPInfo?>);

  @override
  _i7.Future<void> reportBrokenNode({required _i10.ReportBrokenNodeRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportBrokenNode,
          [],
          {#request: request},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserPrefsMarketingConsent({required bool? consent}) => (super.noSuchMethod(
        Invocation.method(
          #setUserPrefsMarketingConsent,
          [],
          {#consent: consent},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getUserPrefsMarketingConsent() => (super.noSuchMethod(
        Invocation.method(
          #getUserPrefsMarketingConsent,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setEmailMarketingConsent({required bool? consent}) => (super.noSuchMethod(
        Invocation.method(
          #setEmailMarketingConsent,
          [],
          {#consent: consent},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.BannerType>> getShownBanners() => (super.noSuchMethod(
        Invocation.method(
          #getShownBanners,
          [],
        ),
        returnValue: _i7.Future<List<_i11.BannerType>>.value(<_i11.BannerType>[]),
        returnValueForMissingStub: _i7.Future<List<_i11.BannerType>>.value(<_i11.BannerType>[]),
      ) as _i7.Future<List<_i11.BannerType>>);

  @override
  _i7.Future<void> setShownBanners(List<_i11.BannerType>? banners) => (super.noSuchMethod(
        Invocation.method(
          #setShownBanners,
          [banners],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disconnectAllDevices() => (super.noSuchMethod(
        Invocation.method(
          #disconnectAllDevices,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SubscriptionStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionStore extends _i1.Mock implements _i12.SubscriptionStore {
  @override
  set isAvailableFuture(_i5.ObservableFuture<_i3.SubscriptionConfigResponse>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #isAvailableFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set verifySubscriptionFuture(_i5.ObservableFuture<_i13.Subscription>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #verifySubscriptionFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set subscriptionFuture(_i5.ObservableFuture<_i13.Subscription>? value) => super.noSuchMethod(
        Invocation.setter(
          #subscriptionFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.PurchasableProduct get monthlyProduct => (super.noSuchMethod(
        Invocation.getter(#monthlyProduct),
        returnValue: _FakePurchasableProduct_2(
          this,
          Invocation.getter(#monthlyProduct),
        ),
        returnValueForMissingStub: _FakePurchasableProduct_2(
          this,
          Invocation.getter(#monthlyProduct),
        ),
      ) as _i4.PurchasableProduct);

  @override
  _i4.PurchasableProduct get highlightedProduct => (super.noSuchMethod(
        Invocation.getter(#highlightedProduct),
        returnValue: _FakePurchasableProduct_2(
          this,
          Invocation.getter(#highlightedProduct),
        ),
        returnValueForMissingStub: _FakePurchasableProduct_2(
          this,
          Invocation.getter(#highlightedProduct),
        ),
      ) as _i4.PurchasableProduct);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);

  @override
  _i14.StoreState get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: _i14.StoreState.loading,
        returnValueForMissingStub: _i14.StoreState.loading,
      ) as _i14.StoreState);

  @override
  _i5.ObservableList<_i4.PurchasableProduct> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: _FakeObservableList_4<_i4.PurchasableProduct>(
          this,
          Invocation.getter(#products),
        ),
        returnValueForMissingStub: _FakeObservableList_4<_i4.PurchasableProduct>(
          this,
          Invocation.getter(#products),
        ),
      ) as _i5.ObservableList<_i4.PurchasableProduct>);

  @override
  _i7.Future<void> initStore() => (super.noSuchMethod(
        Invocation.method(
          #initStore,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> fetchSubscription() => (super.noSuchMethod(
        Invocation.method(
          #fetchSubscription,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isSubscriptionActive() => (super.noSuchMethod(
        Invocation.method(
          #isSubscriptionActive,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> getSubscriptionsConfig() => (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionsConfig,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> getProductsDetails() => (super.noSuchMethod(
        Invocation.method(
          #getProductsDetails,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> subscribeToPackage({required _i15.ProductDetails? product}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPackage,
          [],
          {#product: product},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> redeemCode() => (super.noSuchMethod(
        Invocation.method(
          #redeemCode,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> verifyPurchase(
    String? productId,
    String? price,
    _i15.PurchaseDetails? purchaseDetails,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPurchase,
          [
            productId,
            price,
            purchaseDetails,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> retryVerificationProcess() => (super.noSuchMethod(
        Invocation.method(
          #retryVerificationProcess,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<(bool, String?)> checkForExistingSubscription() => (super.noSuchMethod(
        Invocation.method(
          #checkForExistingSubscription,
          [],
        ),
        returnValue: _i7.Future<(bool, String?)>.value((false, null)),
        returnValueForMissingStub: _i7.Future<(bool, String?)>.value((false, null)),
      ) as _i7.Future<(bool, String?)>);

  @override
  _i7.Future<void> manageSubscription() => (super.noSuchMethod(
        Invocation.method(
          #manageSubscription,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RemoteConfigStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigStore extends _i1.Mock implements _i16.RemoteConfigStore {
  @override
  _i5.ObservableFuture<Map<String, dynamic>> get configFuture => (super.noSuchMethod(
        Invocation.getter(#configFuture),
        returnValue: _FakeObservableFuture_5<Map<String, dynamic>>(
          this,
          Invocation.getter(#configFuture),
        ),
        returnValueForMissingStub: _FakeObservableFuture_5<Map<String, dynamic>>(
          this,
          Invocation.getter(#configFuture),
        ),
      ) as _i5.ObservableFuture<Map<String, dynamic>>);

  @override
  set configFuture(_i5.ObservableFuture<Map<String, dynamic>>? value) => super.noSuchMethod(
        Invocation.setter(
          #configFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isServiceAvailable => (super.noSuchMethod(
        Invocation.getter(#isServiceAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get isServiceAvailableMessage => (super.noSuchMethod(
        Invocation.getter(#isServiceAvailableMessage),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#isServiceAvailableMessage),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#isServiceAvailableMessage),
        ),
      ) as String);

  @override
  bool get hideDeleteAccount => (super.noSuchMethod(
        Invocation.getter(#hideDeleteAccount),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideKillSwitch => (super.noSuchMethod(
        Invocation.getter(#hideKillSwitch),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get minMacosBuildNumber => (super.noSuchMethod(
        Invocation.getter(#minMacosBuildNumber),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minMacosBuildNumber),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minMacosBuildNumber),
        ),
      ) as String);

  @override
  String get minWindowsStandAloneBuildNumber => (super.noSuchMethod(
        Invocation.getter(#minWindowsStandAloneBuildNumber),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minWindowsStandAloneBuildNumber),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minWindowsStandAloneBuildNumber),
        ),
      ) as String);

  @override
  String get minWindowsBuildNumber => (super.noSuchMethod(
        Invocation.getter(#minWindowsBuildNumber),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minWindowsBuildNumber),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minWindowsBuildNumber),
        ),
      ) as String);

  @override
  String get minAndroidBuildNumber => (super.noSuchMethod(
        Invocation.getter(#minAndroidBuildNumber),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minAndroidBuildNumber),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minAndroidBuildNumber),
        ),
      ) as String);

  @override
  String get minIosBuildNumber => (super.noSuchMethod(
        Invocation.getter(#minIosBuildNumber),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minIosBuildNumber),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#minIosBuildNumber),
        ),
      ) as String);

  @override
  bool get hideReedemCode => (super.noSuchMethod(
        Invocation.getter(#hideReedemCode),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideMalwareBlocker => (super.noSuchMethod(
        Invocation.getter(#hideMalwareBlocker),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideNotSafeContentBlocker => (super.noSuchMethod(
        Invocation.getter(#hideNotSafeContentBlocker),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get malwareBlockerDnsAddress => (super.noSuchMethod(
        Invocation.getter(#malwareBlockerDnsAddress),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#malwareBlockerDnsAddress),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#malwareBlockerDnsAddress),
        ),
      ) as String);

  @override
  String get notSafeContentBlockerDnsAddress => (super.noSuchMethod(
        Invocation.getter(#notSafeContentBlockerDnsAddress),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#notSafeContentBlockerDnsAddress),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#notSafeContentBlockerDnsAddress),
        ),
      ) as String);

  @override
  bool get showVpnPrivacyPolicyPage => (super.noSuchMethod(
        Invocation.getter(#showVpnPrivacyPolicyPage),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get pricingMonthly => (super.noSuchMethod(
        Invocation.getter(#pricingMonthly),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get mqttExperiment => (super.noSuchMethod(
        Invocation.getter(#mqttExperiment),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get dataCenterCountries => (super.noSuchMethod(
        Invocation.getter(#dataCenterCountries),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get showSalesView => (super.noSuchMethod(
        Invocation.getter(#showSalesView),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, String> get asUserProperties => (super.noSuchMethod(
        Invocation.getter(#asUserProperties),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);
}
