// Mocks generated by Mockito 5.4.4 from annotations
// in mysterium_vpn/test/stores/locations_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i4;

import 'package:flutter/material.dart' as _i17;
import 'package:flutter/widgets.dart' as _i14;
import 'package:mobx/mobx.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mysterium_vpn/common/enums/enums.dart' as _i9;
import 'package:mysterium_vpn/common/enums/indicator_type.dart' as _i15;
import 'package:mysterium_vpn/models/ip_info.dart' as _i10;
import 'package:mysterium_vpn/models/location.dart' as _i2;
import 'package:mysterium_vpn/models/report_broken_node_request.dart' as _i11;
import 'package:mysterium_vpn/models/user_data.dart' as _i8;
import 'package:mysterium_vpn/services/api/api_service.dart' as _i6;
import 'package:mysterium_vpn/services/data/filter_service.dart' as _i12;
import 'package:mysterium_vpn/services/data/local/shared_preferences_service.dart' as _i16;
import 'package:mysterium_vpn/stores/analytics/analytics_store.dart' as _i13;
import 'package:mysterium_vpn/stores/locale_store.dart' as _i18;
import 'package:vpn_api/vpn_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPNLocations_0 extends _i1.SmartFake implements _i2.VPNLocations {
  _FakeVPNLocations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWireguardConnectResponse_1 extends _i1.SmartFake
    implements _i3.WireguardConnectResponse {
  _FakeWireguardConnectResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_3 extends _i1.SmartFake implements _i5.ReactiveContext {
  _FakeReactiveContext_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  @override
  _i7.Future<void> setNotificationsApproval({required bool? approval}) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationsApproval,
          [],
          {#approval: approval},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.Approval> getNotificationsApproval() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationsApproval,
          [],
        ),
        returnValue: _i7.Future<_i8.Approval>.value(_i8.Approval.approved),
        returnValueForMissingStub: _i7.Future<_i8.Approval>.value(_i8.Approval.approved),
      ) as _i7.Future<_i8.Approval>);

  @override
  _i7.Future<_i2.VPNLocations> fetchVPNLocations([_i9.IPType? ipType]) => (super.noSuchMethod(
        Invocation.method(
          #fetchVPNLocations,
          [ipType],
        ),
        returnValue: _i7.Future<_i2.VPNLocations>.value(_FakeVPNLocations_0(
          this,
          Invocation.method(
            #fetchVPNLocations,
            [ipType],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i2.VPNLocations>.value(_FakeVPNLocations_0(
          this,
          Invocation.method(
            #fetchVPNLocations,
            [ipType],
          ),
        )),
      ) as _i7.Future<_i2.VPNLocations>);

  @override
  _i7.Future<void> addRecentLocation(_i2.VPNLocation? location) => (super.noSuchMethod(
        Invocation.method(
          #addRecentLocation,
          [location],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.VPNLocation>> getRecentLocations() => (super.noSuchMethod(
        Invocation.method(
          #getRecentLocations,
          [],
        ),
        returnValue: _i7.Future<List<_i2.VPNLocation>>.value(<_i2.VPNLocation>[]),
        returnValueForMissingStub: _i7.Future<List<_i2.VPNLocation>>.value(<_i2.VPNLocation>[]),
      ) as _i7.Future<List<_i2.VPNLocation>>);

  @override
  _i7.Future<_i3.WireguardConnectResponse> fetchVpnConfig(
          {required _i3.WireguardConnectRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVpnConfig,
          [],
          {#request: request},
        ),
        returnValue: _i7.Future<_i3.WireguardConnectResponse>.value(_FakeWireguardConnectResponse_1(
          this,
          Invocation.method(
            #fetchVpnConfig,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.WireguardConnectResponse>.value(_FakeWireguardConnectResponse_1(
          this,
          Invocation.method(
            #fetchVpnConfig,
            [],
            {#request: request},
          ),
        )),
      ) as _i7.Future<_i3.WireguardConnectResponse>);

  @override
  _i7.Future<_i10.IPInfo?> getIPAdress() => (super.noSuchMethod(
        Invocation.method(
          #getIPAdress,
          [],
        ),
        returnValue: _i7.Future<_i10.IPInfo?>.value(),
        returnValueForMissingStub: _i7.Future<_i10.IPInfo?>.value(),
      ) as _i7.Future<_i10.IPInfo?>);

  @override
  _i7.Future<void> reportBrokenNode({required _i11.ReportBrokenNodeRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportBrokenNode,
          [],
          {#request: request},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserPrefsMarketingConsent({required bool? consent}) => (super.noSuchMethod(
        Invocation.method(
          #setUserPrefsMarketingConsent,
          [],
          {#consent: consent},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> getUserPrefsMarketingConsent() => (super.noSuchMethod(
        Invocation.method(
          #getUserPrefsMarketingConsent,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setEmailMarketingConsent({required bool? consent}) => (super.noSuchMethod(
        Invocation.method(
          #setEmailMarketingConsent,
          [],
          {#consent: consent},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.BannerType>> getShownBanners() => (super.noSuchMethod(
        Invocation.method(
          #getShownBanners,
          [],
        ),
        returnValue: _i7.Future<List<_i9.BannerType>>.value(<_i9.BannerType>[]),
        returnValueForMissingStub: _i7.Future<List<_i9.BannerType>>.value(<_i9.BannerType>[]),
      ) as _i7.Future<List<_i9.BannerType>>);

  @override
  _i7.Future<void> setShownBanners(List<_i9.BannerType>? banners) => (super.noSuchMethod(
        Invocation.method(
          #setShownBanners,
          [banners],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [FilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterService extends _i1.Mock implements _i12.FilterService {
  @override
  List<_i2.VPNLocation> filterLocations(
    List<_i2.VPNLocation>? data, {
    String? keyword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterLocations,
          [data],
          {#keyword: keyword},
        ),
        returnValue: <_i2.VPNLocation>[],
        returnValueForMissingStub: <_i2.VPNLocation>[],
      ) as List<_i2.VPNLocation>);
}

/// A class which mocks [AnalyticsStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsStore extends _i1.Mock implements _i13.AnalyticsStore {
  @override
  _i7.Future<void> logError({
    required Object? err,
    StackTrace? stack,
    Object? reason,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logError,
          [],
          {
            #err: err,
            #stack: stack,
            #reason: reason,
            #fatal: fatal,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i14.NavigatorObserver> navigationObservers() => (super.noSuchMethod(
        Invocation.method(
          #navigationObservers,
          [],
        ),
        returnValue: <_i14.NavigatorObserver>[],
        returnValueForMissingStub: <_i14.NavigatorObserver>[],
      ) as List<_i14.NavigatorObserver>);

  @override
  _i7.Future<void> logEvent(
    _i9.AnalyticsEvent? event, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [event],
          {#parameters: parameters},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserProperty(
    String? name,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [
            name,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setLogin([_i9.GrantType? loginMethod = _i9.GrantType.email]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLogin,
          [loginMethod],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSearchEvent(String? searchTerm) => (super.noSuchMethod(
        Invocation.method(
          #setSearchEvent,
          [searchTerm],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #logMessage,
          [message],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logScreenViewed(String? screenName) => (super.noSuchMethod(
        Invocation.method(
          #logScreenViewed,
          [screenName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logLocationsListScroll() => (super.noSuchMethod(
        Invocation.method(
          #logLocationsListScroll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logThemeChange(String? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #logThemeChange,
          [themeMode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logLanguageChange(String? language) => (super.noSuchMethod(
        Invocation.method(
          #logLanguageChange,
          [language],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setConsents() => (super.noSuchMethod(
        Invocation.method(
          #setConsents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logProductSelected(
    String? productId,
    List<String>? productIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logProductSelected,
          [
            productId,
            productIds,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logBannerClose(_i9.BannerType? banner) => (super.noSuchMethod(
        Invocation.method(
          #logBannerClose,
          [banner],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logBannerClick(_i9.BannerType? banner) => (super.noSuchMethod(
        Invocation.method(
          #logBannerClick,
          [banner],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logLocationTabOpen(_i9.IPType? locationType) => (super.noSuchMethod(
        Invocation.method(
          #logLocationTabOpen,
          [locationType],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logConnect(
    _i2.VPNLocation? location, [
    _i9.AnalyticsEvent? event,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #logConnect,
          [
            location,
            event,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logDisconnect(
    _i2.VPNLocation? location, [
    _i9.AnalyticsEvent? event,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDisconnect,
          [
            location,
            event,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logConnectSuccess({
    required _i2.VPNLocation? location,
    required Duration? time,
    required bool? isRefresh,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logConnectSuccess,
          [],
          {
            #location: location,
            #time: time,
            #isRefresh: isRefresh,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logConnectFailure({
    required Duration? time,
    required String? error,
    required String? errorType,
    int? errorCode,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logConnectFailure,
          [],
          {
            #time: time,
            #error: error,
            #errorType: errorType,
            #errorCode: errorCode,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logTooltipClick(_i15.TooltipType? tooltip) => (super.noSuchMethod(
        Invocation.method(
          #logTooltipClick,
          [tooltip],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logAppLaunchEvent() => (super.noSuchMethod(
        Invocation.method(
          #logAppLaunchEvent,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SharedPreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceService extends _i1.Mock implements _i16.SharedPreferenceService {
  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  String? getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  List<String>? getStringList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as List<String>?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as bool?);

  @override
  _i7.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setBool(
    String? key, {
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [key],
          {#value: value},
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool checkExistance(_i9.StorageKeys? key) => (super.noSuchMethod(
        Invocation.method(
          #checkExistance,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Locale getLocale() => (super.noSuchMethod(
        Invocation.method(
          #getLocale,
          [],
        ),
        returnValue: _FakeLocale_2(
          this,
          Invocation.method(
            #getLocale,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeLocale_2(
          this,
          Invocation.method(
            #getLocale,
            [],
          ),
        ),
      ) as _i4.Locale);

  @override
  _i7.Future<bool> setLocale(_i4.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [locale],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setThemeType(_i17.ThemeMode? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeType,
          [themeMode],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setAppInstallDay(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setAppInstallDay,
          [value],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setRemindTimeStamp(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setRemindTimeStamp,
          [value],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setLocationCode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setLocationCode,
          [value],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> setLocation(_i2.VPNLocation? location) => (super.noSuchMethod(
        Invocation.method(
          #setLocation,
          [location],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> setIPInfo(_i10.IPInfo? info) => (super.noSuchMethod(
        Invocation.method(
          #setIPInfo,
          [info],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setIPType(_i9.IPType? type) => (super.noSuchMethod(
        Invocation.method(
          #setIPType,
          [type],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [LocaleStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleStore extends _i1.Mock implements _i18.LocaleStore {
  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);

  @override
  _i4.Locale get currentLocale => (super.noSuchMethod(
        Invocation.getter(#currentLocale),
        returnValue: _FakeLocale_2(
          this,
          Invocation.getter(#currentLocale),
        ),
        returnValueForMissingStub: _FakeLocale_2(
          this,
          Invocation.getter(#currentLocale),
        ),
      ) as _i4.Locale);

  @override
  _i7.Future<void> setLocale(_i4.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [locale],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
