enum StorageKeys {
  countryCode,
  languageCode,
  themeMype,
  subscriptionPlanProductId,
  subscriptionPlanPurchaseId,
  emailCommunicationApproval,
  notificationsApproval,
  accessToken,
  username,
  userId,
  appLink,
  wireguardPublicKey,
  wireguardPrivateKey,
  codeChallenge,
  codeVerifier,
}
