// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => macos,
      TargetPlatform.windows => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      TargetPlatform.linux => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      _ => throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.'),
    };
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOAJHXgab-vtJILPhVeREmsD8Dc8-EZY',
    appId: '1:104590535697:web:f7b7ea7844bbec59f355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    authDomain: 'new-mysterium-vpn.firebaseapp.com',
    storageBucket: 'new-mysterium-vpn.appspot.com',
    measurementId: 'G-NRGS9M0J5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmRjjve4OlKZ4UBx9vGAzOwfkEbQw4j8',
    appId: '1:104590535697:android:c0320e37547693f7f355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpAxPxcYK5BfP_9z2aT2-avOI3qZ5Py0',
    appId: '1:104590535697:ios:30362bcd1ee53392f355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
    iosClientId: '104590535697-qlqv1si8krj17nvto6mrfgujhm81inti.apps.googleusercontent.com',
    iosBundleId: 'com.mysteriumvpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfpAxPxcYK5BfP_9z2aT2-avOI3qZ5Py0',
    appId: '1:104590535697:ios:30362bcd1ee53392f355b0',
    messagingSenderId: '104590535697',
    projectId: 'new-mysterium-vpn',
    storageBucket: 'new-mysterium-vpn.appspot.com',
    iosClientId: '104590535697-qlqv1si8krj17nvto6mrfgujhm81inti.apps.googleusercontent.com',
    iosBundleId: 'com.mysteriumvpn',
  );
}
