// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => macos,
      TargetPlatform.windows => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      TargetPlatform.linux => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      _ => throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.'),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWAD1DgEGtBxYtCcZ-WCfkk6iDL7KniA4',
    appId: '1:139303438361:android:e42d01c6f6f04470b7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Z7KPJJDOEFgIeGue8IFZdBkmq_6cv4U',
    appId: '1:139303438361:ios:d2ba132c760888aeb7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
    iosClientId: '139303438361-qi0fhvfmd6jeqef86q0b20dqq5ind2nd.apps.googleusercontent.com',
    iosBundleId: 'com.mysteriumvpn.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Z7KPJJDOEFgIeGue8IFZdBkmq_6cv4U',
    appId: '1:139303438361:ios:d2ba132c760888aeb7c288',
    messagingSenderId: '139303438361',
    projectId: 'mysterium-vpn-test',
    storageBucket: 'mysterium-vpn-test.appspot.com',
    iosClientId: '139303438361-qi0fhvfmd6jeqef86q0b20dqq5ind2nd.apps.googleusercontent.com',
    iosBundleId: 'com.mysteriumvpn.test',
  );
}
