#!/usr/bin/env bash
#
# block-udp.sh — temporarily block UDP on macOS, to test how the VPN client
# behaves on networks that only allow TCP (hotel / corporate Wi-Fi, some mobile
# carriers). Typical use: verify the WireGuard -> OpenVPN-TCP fallback path.
#
#   ./scripts/block-udp.sh stun     block ONLY the STUN probe (UDP 3478). This
#                                   is the mode that reproduces the in-app
#                                   "WireGuard connection blocked" dialog — see
#                                   REPRODUCING THE FALLBACK DIALOG below.
#   ./scripts/block-udp.sh vpn      block the usual VPN UDP ports only
#   ./scripts/block-udp.sh all      block all outbound UDP except DNS/mDNS/DHCP
#   ./scripts/block-udp.sh bridge   block UDP from devices sharing this Mac's
#                                   connection (test a phone — see NOTES)
#   ./scripts/block-udp.sh status   show what is currently loaded
#   ./scripts/block-udp.sh off      revert everything (see REVERTING)
#
# REPRODUCING THE FALLBACK DIALOG
#   The app decides UDP is blocked by sending a STUN binding request to
#   echo.mysterium.network:3478 *after* the tunnel is already up
#   (rest_api_service.dart). So the dialog needs a live WireGuard tunnel whose
#   inner UDP does not work.
#
#   `vpn` and `all` do NOT reproduce it: both block UDP 51820, so WireGuard
#   never connects, the connect attempt fails first, and the probe never runs.
#   That is a real product gap (a hard-blocked network shows a generic connect
#   error, not the dialog) but it is not what this script is for.
#
#   `stun` blocks only UDP 3478, leaving 51820 alone. WireGuard connects
#   normally, DNS resolves echo.mysterium.network, and the probe then times out
#   after 5s — which is exactly the signal the app acts on. The rule carries no
#   interface clause on purpose: the probe is sent inside the tunnel, so it must
#   be matched on the utun interface, not the physical one.
#
# REVERTING
#   `off` reloads the system ruleset from /etc/pf.conf and disables pf again —
#   but only if pf was disabled before this script ran. If something else on the
#   machine had pf enabled already (Docker, Little Snitch, a corporate agent),
#   the script leaves pf enabled and only drops its own rules, so it does not
#   break that other tool.
#   Nothing here survives a reboot: rebooting also reverts.
#
# NOTES
#   - Everything runs through sudo; you will be prompted for a password.
#   - `all` deliberately still permits DNS (53), mDNS (5353) and DHCP (67/68).
#     Blocking those too makes the machine look "offline" instead of "no UDP",
#     which turns into a misdiagnosis.
#   - pf filters at the network interface, so a tunnel that is already connected
#     goes quiet rather than failing instantly. Reconnect after loading.
#   - `bridge` expects macOS Internet Sharing to be on
#     (System Settings > General > Sharing > Internet Sharing) with the phone
#     joined to the Mac's hotspot. Override the interface if it is not the
#     default bridge100:  IFACE=bridge101 ./scripts/block-udp.sh bridge
#
set -euo pipefail

MODE="${1:-}"
IFACE="${IFACE:-bridge100}"

# Marker recording that *this* script was the one that enabled pf, so `off`
# knows whether it is allowed to disable pf again.
STATE_FILE="${TMPDIR:-/tmp}/.block-udp-pf-enabled-by-script"

# UDP ports used by the VPN protocols we care about.
#   51820 WireGuard | 1194/1195 OpenVPN | 500/4500 IKEv2
VPN_PORTS="{ 51820, 1194, 1195, 500, 4500 }"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script uses pf and only works on macOS." >&2
  exit 1
fi

# No pipeline: under `set -o pipefail` a SIGPIPE from head/grep could report pf
# as disabled while it is running, and `off` would then disable pf out from
# under whatever else had enabled it.
pf_is_enabled() {
  local info
  info="$(sudo pfctl -s info 2>/dev/null || true)"
  [[ "$info" == *"Status: Enabled"* ]]
}

load_rules() {
  # Remember pf's pre-existing state the first time we touch it.
  if [[ ! -f "$STATE_FILE" ]] && ! pf_is_enabled; then
    : > "$STATE_FILE"
  fi

  local ruleset
  ruleset="$(mktemp -t block-udp)"
  # shellcheck disable=SC2064
  trap "rm -f '$ruleset'" EXIT

  # pfctl -f REPLACES the main ruleset, and /etc/pf.conf warns that flushing it
  # breaks the nested anchors system services rely on — Internet Sharing's NAT
  # lives in com.apple/*. So re-declare Apple's anchor point around our rules
  # instead of dropping it. Order follows pf.conf(5): options, normalization,
  # queueing, translation, then filtering.
  cat > "$ruleset" <<RULES
# Generated by scripts/block-udp.sh — safe to delete.
set skip on lo0
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
$1
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
RULES

  echo "Loading:"
  sed 's/^/  /' "$ruleset"
  echo

  # Validate before touching the live ruleset, so a typo cannot leave pf enabled
  # with a half-applied config.
  if ! sudo pfctl -n -f "$ruleset" >/dev/null 2>&1; then
    echo "Ruleset failed to parse — nothing was loaded:" >&2
    sudo pfctl -n -f "$ruleset" 2>&1 | sed 's/^/  /' >&2
    exit 1
  fi

  # -E enables pf and bumps its enable-reference counter; -f loads the ruleset.
  local out status=0
  out="$(sudo pfctl -E -f "$ruleset" 2>&1)" || status=$?
  echo "$out" | grep -vE '^No ALTQ|^pfctl: Use of -f option|^See /etc/pf.conf|^present in the main ruleset|^$' || true
  if [[ $status -ne 0 ]]; then
    echo "pfctl exited $status — the ruleset may not be active." >&2
    exit "$status"
  fi

  echo
  echo "Active. Revert with: $0 off"
}

case "$MODE" in
  stun)
    # Port 3478 only. The tunnel's own traffic is UDP 51820 and is untouched,
    # so WireGuard still connects — it is the probe inside the tunnel that dies.
    load_rules "block drop out proto udp from any to any port 3478"
    ;;
  vpn)
    # pf is last-match-wins, but there is only one rule here.
    load_rules "block drop out proto udp from any to any port $VPN_PORTS"
    ;;
  all)
    # Block first, then pass the exceptions — later matches win without 'quick'.
    load_rules "block drop out proto udp all
pass out proto udp from any to any port 53
pass out proto udp from any to any port 5353
pass out proto udp from any to any port { 67, 68 }"
    ;;
  bridge)
    # Traffic from the shared device *enters* this Mac on the bridge, so the
    # direction is 'in', not 'out'.
    load_rules "block drop in on $IFACE proto udp all
pass in on $IFACE proto udp from any to any port 53
pass in on $IFACE proto udp from any to any port 5353
pass in on $IFACE proto udp from any to any port { 67, 68 }"
    ;;
  status)
    sudo pfctl -s info 2>/dev/null | sed -n '1p'
    echo
    sudo pfctl -s rules 2>/dev/null
    ;;
  off)
    # Put the system ruleset back. If this fails the block rules are still live,
    # so say so rather than claiming success.
    if ! sudo pfctl -f /etc/pf.conf >/dev/null 2>&1; then
      echo "Failed to reload /etc/pf.conf — block rules may still be active." >&2
      sudo pfctl -f /etc/pf.conf 2>&1 | sed 's/^/  /' >&2
      exit 1
    fi
    if [[ -f "$STATE_FILE" ]]; then
      # We enabled pf, so we may disable it. -d clears the reference counter.
      sudo pfctl -d 2>&1 | grep -v '^No ALTQ' || true
      rm -f "$STATE_FILE"
      echo "Reverted: /etc/pf.conf restored, pf disabled."
    else
      echo "Reverted: /etc/pf.conf restored. pf left enabled (it was already on)."
    fi
    ;;
  *)
    # Print the whole leading comment block, however long it grows.
    awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"
    exit 1
    ;;
esac
