on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      product_store_id:
        required: true
        type: string
      product_identity:
        required: true
        type: string
      application_name:
        required: true
        type: string
        default: "Mysterium VPN Test"
      application_logo:
        required: true
        type: string
        default: "assets/logo/dev/desktop.png"
      flavor_dart:
        required: true
        type: string
        default: "DEV"
      standalone_sign:
        required: true
        type: boolean
        default: false

jobs:
  release:
    name: Build & Publish
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install yq using Chocolatey
        run: choco install yq -y

      - name: Setup Flutter Version Management CLI
        run: choco install yq fvm -y

      - name: Install Flutter SDK
        run: echo yes | fvm use

      - name: Print Flutter SDK version
        run: fvm flutter --version

      - name: Install dependencies
        run: make init

      - name: Replace version
        run: |
          fvm dart run cider version "${{ inputs.build_version }}+${{ inputs.build_number }}"
          git diff

      - name: Build Windows app
        run: fvm flutter build windows --no-pub --release --dart-define "FLAVOR=${{ inputs.flavor_dart }}"

      # Sign DEV builds with self-signed test certificate for QA process.
      # Documentation: https://github.com/YehudaKremer/msix?tab=readme-ov-file#%EF%B8%8F-signing-options
      # Instructions how to use installer which such certificate: https://medium.com/flutter-community/publishing-flutter-windows-apps-to-microsoft-partner-center-with-codemagic-b1962575510c#f083
      - name: Build Windows installer
        if: ${{ inputs.standalone_sign != true }}
        run: |
          fvm dart run msix:create `
            --build-windows false --install-certificate false --output-name "Mysterium VPN" `
            --display-name "${{ inputs.application_name }}" --logo-path "${{ inputs.application_logo }}" `
            --sign-msix "true"
        continue-on-error: true
      - name: Build Windows installer
        if: ${{ inputs.standalone_sign == true }}
        run: |
          fvm dart run msix:create `
            --build-windows false --install-certificate false --output-name "Mysterium VPN" `
            --display-name "${{ inputs.application_name }}" --logo-path "${{ inputs.application_logo }}" `
            --sign-msix false --publisher "CN=UAB MN Technologijos, O=UAB MN Technologijos, L=Vilnius, S=Vilniaus, C=LT"
        continue-on-error: true

      - name: Sign Windows installer
        if: ${{ inputs.standalone_sign == true }}
        uses: azure/trusted-signing-action@v0.5.1
        with:
          azure-tenant-id: ${{ vars.MICROSOFT_AZURE_AD_TENANT_ID }}
          azure-client-id: ${{ vars.MICROSOFT_AZURE_SIGNING_ClIENT_ID }}
          azure-client-secret: ${{ secrets.MICROSOFT_AZURE_SIGNING_ClIENT_SECRET }}
          endpoint: https://neu.codesigning.azure.net/
          trusted-signing-account-name: ${{ vars.MICROSOFT_AZURE_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ vars.MICROSOFT_AZURE_SIGNING_PROFILE_NAME }}
          files-folder: build/windows/x64/runner/Release
          files-folder-filter: msix
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          cache-dependencies: true
        continue-on-error: true

      - name: Upload to Github
        uses: actions/upload-artifact@v4
        with:
          name: Windows app (Standalone)
          path: build/windows/x64/runner/Release/Mysterium VPN.msix
          if-no-files-found: error
        continue-on-error: true

      - name: Build Windows installer
        run: |
          fvm dart run msix:create `
            --build-windows false --install-certificate false --output-name "Mysterium VPN" `
            --display-name "${{ inputs.application_name }}" --logo-path "${{ inputs.application_logo }}" `
            --store --identity-name "${{ inputs.product_identity }}" --publisher "CN=B6C98289-B62E-4315-9F65-9B59DB0FC5AC" --publisher-display-name "UAB MN Technologijos"
        continue-on-error: true

      - name: Upload to Github
        uses: actions/upload-artifact@v4
        with:
          name: Windows app (Store)
          path: build/windows/x64/runner/Release/Mysterium VPN.msix
          if-no-files-found: error
        continue-on-error: true

      - name: Download Microsoft Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1
      - name: Setup Microsoft Store Developer CLI
        run: |
          msstore reconfigure --tenantId "${{ vars.MICROSOFT_AZURE_AD_TENANT_ID }}" --clientId "${{ vars.MICROSOFT_AZURE_AD_ClIENT_ID }}" --clientSecret "${{ secrets.MICROSOFT_AZURE_AD_CLIENT_SECRET }}" --sellerId "${{ vars.MICROSOFT_PARTNER_CENTER_SELLER_ID }}"
          msstore info
        continue-on-error: true
      - name: Publish to Microsoft Store
        run: |
          msstore submission status ${{ inputs.product_store_id }} -v
          msstore publish --inputDirectory "build/windows/x64/runner/Release" --appId ${{ inputs.product_store_id }} --noCommit -v
          msstore submission status ${{ inputs.product_store_id }} -v
        continue-on-error: true
#      - name: Publish to Microsoft Store (commit right away)
#        run: msstore submission publish ${{ inputs.product_store_id }}
#        continue-on-error: true
