on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      bundle_id:
        required: true
        type: string
      product_name:
        required: true
        type: string
        default: "Mysterium VPN Test"
      flavor:
        required: true
        type: string
        default: "dev"
      env_file:
        required: true
        type: string
        default: ".env.dev"

jobs:
  # macOS Build
  # Based on documentation https://docs.flutter.dev/deployment/macos#create-a-build-archive-with-codemagic-cli-tools
  # And tutorial https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#code-signing
  release:
    name: Build & Publish
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Replace Git URL in pubspec.yaml with PAT
        run: |
          sed -i.bak "s|git@github.com:mysteriumnetwork/openvpn_dart.git|https://${GITHUB_PAT}@github.com/mysteriumnetwork/openvpn_dart.git|g" pubspec.yaml
        env:
          GITHUB_PAT: ${{ secrets.OPENVPI_GITHUB_PAT }}

      - name: Set up XCode
        run: sudo xcode-select --switch /Applications/Xcode_16.1.0.app

      - name: Setup Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1.0

      - name: Install Flutter SDK
        run: echo yes | fvm use

      - name: Print Flutter SDK version
        run: fvm flutter --version

      - name: Install Codemagic CLI tools
        run: |
          python -m pip install codemagic-cli-tools
          codemagic-cli-tools version
          codemagic-cli-tools installed-tools

      - name: Set up keychain
        run: |
          keychain initialize
          keychain get-default

      # Signing files are imported to keychain from:
      #  ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      #  ls -la ~/Library/MobileDevice/Certificates/
      - name: Fetch signing files
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APPLE_APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          app-store-connect fetch-signing-files "${{ inputs.bundle_id }}" --platform MAC_OS --type MAC_APP_STORE --certificate-key "${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}" --create
          keychain add-certificates

      - name: Fetch Installer Distribution certificates
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APPLE_APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          app-store-connect certificates list --type MAC_INSTALLER_DISTRIBUTION --certificate-key "${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}" --save \
          || app-store-connect certificates create --type MAC_INSTALLER_DISTRIBUTION --certificate-key "${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}" --save
          keychain add-certificates

      - name: Set up signing preferences on Xcode project
        run: |
          keychain list-certificates
          xcode-project use-profiles --project macos/Runner.xcodeproj --export-options-plist macos/export_options.plist
          git status
          git diff

      - name: Install dependencies
        run: make init

      - name: Replace version
        run: |
          fvm dart run cider version "${{ inputs.build_version }}+${{ inputs.build_number }}"
          git diff

      - name: Build macOS app
        run: fvm flutter build macos --no-pub --release --flavor "${{ inputs.flavor }}" --dart-define-from-file="${{ inputs.env_file }}"

      - name: Build macOS installer
        run: |
          xcrun productbuild --component "${{ inputs.product_name }}.app" /Applications/ unsigned.pkg
          xcrun productsign --sign "$(keychain list-certificates | jq '[.[] | select(.common_name | contains("Mac Developer Installer")) | .common_name][0]' | xargs)" unsigned.pkg "Mysterium VPN.pkg"
        working-directory: build/macos/Build/Products/Release-${{ inputs.flavor }}

      - name: Publish to Apple Store
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APPLE_APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
        run: app-store-connect publish --path "build/macos/Build/Products/Release-${{ inputs.flavor }}/Mysterium VPN.pkg" --platform MAC_OS

      - name: Post Set up keychain
        run: |
          keychain delete
          keychain use-login
          keychain list-certificates
        if: always()
