name: CD (after release)

on:
  workflow_dispatch:

jobs:
  release:
    name: Fix release after it has been approved in stores
    runs-on: ubuntu-latest

    steps:
      - name: Install ConfigCat CLI
        run: |
          sudo snap install configcat
          configcat setup --username ${{ secrets.CONFIGCAT_API_USER }} --password ${{ secrets.CONFIGCAT_API_PASS }}

      - name: Reset "hideDeleteAccount" to defaults
        run: |
          positions=`configcat flag-v2 value show --flag-id 927243 --json | jq '.values[] | select(.environmentId=="08dcf9bb-7e45-4853-8b0e-0129d6009a4e") | .targetingRules | range(length) as $i | select(.[$i].conditions[].userCondition.comparisonAttribute == "version") | $i + 1'`
          for position in $positions; do
            configcat flag-v2 targeting rule rm --flag-id 927243 -e 08dcf9bb-7e45-4853-8b0e-0129d6009a4e --rule-position 1
          done
