name: CD (after release)

on:
  workflow_dispatch:
    inputs:
      version:
        description: (Optional) Release version e.g. 1.0.0. Leave empty to auto-detect the latest release.
        required: false
        type: string

jobs:

  release:
    name: Fix release after it has been approved in stores
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest release
        id: fetch-latest
        if: ${{ github.event.inputs.version == '' }}
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - name: Decide build version
        id: calculate-version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "Using provided release version: ${{ github.event.inputs.version }}"
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "No release input provided, using fetched release: ${{ steps.fetch-latest.outputs.tag_name }}"
            echo "version=${{ steps.fetch-latest.outputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Debug
        run: |
          echo "Using provided release version: ${{ github.event.inputs.version }}"
          echo "No release input provided, using fetched release: ${{ steps.fetch-latest.outputs.tag_name }}"