name: Auto Assign Task
on:
  push:
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Get the column ID
        run: |
          gh api graphql -f query='                                                                                                  
            query{
            organization(login: "mysteriumnetwork"){
                                  projectV2(number: 28) {
                                    id title
            }
          }
          }'
