name: Build (iOS)

on:
  push:
    branches:
      - master

jobs:

  # iOS Build
  # Base on documentation https://docs.flutter.dev/deployment/ios#create-a-build-archive-with-codemagic-cli-tools
  # And tutorial at https://blog.codemagic.io/deploy-your-app-to-app-store-with-codemagic-cli-tools-and-github-actions/
  build_ios:
    name: Publish iOS app to TestFlight
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install Codemagic CLI tools
        run: |
          python -m pip install codemagic-cli-tools
          codemagic-cli-tools version
          codemagic-cli-tools installed-tools

      - name: Set up keychain
        run: |
          keychain initialize
          keychain get-default

      # Signing files are imported to keychain from:
      #  ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      #  ls -la ~/Library/MobileDevice/Certificates/
      - name: Fetch signing files
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APPLE_APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          app-store-connect fetch-signing-files "com.mysteriumvpn.test" --platform IOS --type IOS_APP_STORE --certificate-key "${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}" --create
          keychain add-certificates

      - name: Set up signing preferences on Xcode project
        run: |
          keychain list-certificates
          xcode-project use-profiles --project ios/Runner.xcodeproj --export-options-plist ios/export_options.plist
          git status
          git diff
          cat ios/export_options.plist

      - name: Replace version
        run: |
          sed -i.bak "s/^version:.*/version: 0.0.0-dev+${{ github.run_number }}/" pubspec.yaml
          git diff

      - name: Install dependencies
        run: flutter pub get

      - name: Generate
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Install Pods
        run: pod install
        working-directory: ios

      - name: Build iOS app
        run: |
          flutter build ipa --no-pub --release --flavor "dev" --dart-define FLAVOR=DEV --export-options-plist=ios/export_options.plist
          cat build/ios/ipa/ExportOptions.plist

      # Published as TestFlight build of separate application to https://appstoreconnect.apple.com/apps/6450715542/distribution/ios/version/inflight
      - name: Publish to TestFlight
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APPLE_APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
        run: app-store-connect publish --path "build/ios/ipa/Mysterium VPN.ipa" --platform IOS

      - name: Post Set up keychain
        run: |
          keychain delete
          keychain use-login
          keychain list-certificates
        if: always()