name: CD

on:
  release:
    types: [created]

jobs:

  # Publish build of application to https://appstoreconnect.apple.com/apps/6446624307/distribution/ios/version/inflight
  release_ios:
    name: Release iOS app
    uses: ./.github/workflows/_build-ios.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ github.run_number }}
      bundle_id: com.mysteriumvpn
      flavor: "prod"
      flavor_dart: "PROD"
    secrets: inherit

  # Publish build of application to https://appstoreconnect.apple.com/apps/6446624307/distribution/macos/version/inflight
  release_macos:
    name: Release macOS app
    uses: ./.github/workflows/_build-macos.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ github.run_number }}
      bundle_id: com.mysteriumvpn
      product_name: "Mysterium VPN"
      flavor: "prod"
      flavor_dart: "PROD"
    secrets: inherit

  # Publish build of application to https://play.google.com/console/u/0/developers/7955390843158584488/app/4973980590971676436/bundle-explorer-selector
  release_android:
    name: Release Android app
    uses: ./.github/workflows/_build-android.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ github.run_number }}
      package_name: com.mysteriumvpn.android
      package_track: internal
      flavor: "prod"
      flavor_dart: "PROD"
    secrets: inherit