name: CD

on:
  release:
    types: [created]

jobs:

  setup:
    name: Setup release
    runs-on: ubuntu-latest
    outputs:
      release_build: ${{ steps.calculate-build.outputs.build }}
    steps:
      - name: Decide build number
        id: calculate-build
        run: echo "build=$(( ${{ github.run_number }} + 100 ))" >> "$GITHUB_OUTPUT"

  # Publish build of application to https://appstoreconnect.apple.com/apps/6446624307/distribution/ios/version/inflight
  release_ios:
    needs: [setup]
    name: Release iOS app
    uses: ./.github/workflows/_build-ios.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ needs.setup.outputs.release_build }}
      bundle_id: com.mysteriumvpn
      flavor: "prod"
      env_file: ".env.prod"
    secrets: inherit

  # Publish build of application to https://appstoreconnect.apple.com/apps/6446624307/distribution/macos/version/inflight
  release_macos:
    needs: [setup]
    name: Release macOS app
    uses: ./.github/workflows/_build-macos.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ needs.setup.outputs.release_build }}
      bundle_id: com.mysteriumvpn
      product_name: "Mysterium VPN"
      flavor: "prod"
      env_file: ".env.prod"
    secrets: inherit

  # Publish build of application to https://play.google.com/console/u/0/developers/7955390843158584488/app/4973980590971676436/bundle-explorer-selector
  release_android:
    needs: [setup]
    name: Release Android app
    uses: ./.github/workflows/_build-android.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ needs.setup.outputs.release_build }}
      package_name: com.mysteriumvpn.android
      package_track: internal
      package_status: draft
      flavor: "prod"
      env_file: ".env.prod"
    secrets: inherit

  # Publish build of application to https://partner.microsoft.com/en-us/dashboard/products/9NGWJCZSB5MK/overview
  release_windows:
    needs: [setup]
    name: Release Windows app
    uses: ./.github/workflows/_build-windows.yml
    with:
      build_version: ${{ github.event.release.tag_name }}
      build_number: ${{ needs.setup.outputs.release_build }}
      product_store_id: "9NGWJCZSB5MK"
      product_identity: "UABMNTechnologijos.MysteriumVPN"
      application_name: "Mysterium VPN"
      application_logo: "assets/logo/prod/desktop.png"
      env_file: ".env.prod"
      standalone_sign: true
      standalone_keyvault_certificate: "mysteriumvpn"
      protocol_activation: "mysteriumvpn"
    secrets: inherit

  release:
    needs: [ release_windows ]
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows (Standalone) artifact
        uses: actions/download-artifact@v8
        with:
          name: Windows app (Standalone)
          path: ./release

      - name: Publish assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ./release/MysteriumVPN.msix

  release_public:
    needs: [ release_windows ]
    name: Publish public release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Windows (Standalone) artifact
        uses: actions/download-artifact@v8
        with:
          name: Windows app (Standalone)
          path: ./release

      - name: Publish assets to public release
        uses: softprops/action-gh-release@v2
        with:
          repository: mysteriumnetwork/mysterium-vpn-release
          tag_name: ${{ github.event.release.tag_name }}
          files: ./release/MysteriumVPN.msix
          token: ${{ secrets.GH_RELEASE_PAT }}

  configure:
    name: Fix release to pass review in app stores
    runs-on: ubuntu-latest
    steps:
      - name: Install ConfigCat CLI
        run: |
          sudo snap install configcat
          configcat setup --username ${{ secrets.CONFIGCAT_API_USER }} --password ${{ secrets.CONFIGCAT_API_PASS }}
      - name: Configure "hideDeleteAccount" - show button
        run: |
          configcat flag-v2 targeting rule create user --flag-id 587567 -e 08dcf9bb-7e45-4853-8b0e-0129d6009a4e --attribute version --comparator textEquals --comparison-value "${{ github.event.release.tag_name }}" --served-value false
          position=`configcat flag-v2 value show --flag-id 587567 --json | jq '.values[] | select(.environmentId=="08dcf9bb-7e45-4853-8b0e-0129d6009a4e") | .targetingRules | range(length) as $i | select(.[$i].conditions[].userCondition.comparisonAttribute == "version" and .[$i].conditions[].userCondition.comparisonValue.stringValue == "${{ github.event.release.tag_name }}") | $i + 1'`
          configcat flag-v2 targeting condition add user --flag-id 587567 -e 08dcf9bb-7e45-4853-8b0e-0129d6009a4e --rule-position $position --attribute platform --comparator containsAnyOf --comparison-value "macos:" --comparison-value "ios:"
      - name: Configure "pricingMonthly" - no monthly plan
        run: |
          configcat flag-v2 targeting rule create user --flag-id 614140 -e 08dcf9bb-7e45-4853-8b0e-0129d6009a4e --attribute version --comparator textEquals --comparison-value "${{ github.event.release.tag_name }}" --served-value false
          position=`configcat flag-v2 value show --flag-id 614140 --json | jq '.values[] | select(.environmentId=="08dcf9bb-7e45-4853-8b0e-0129d6009a4e") | .targetingRules | range(length) as $i | select(.[$i].conditions[].userCondition.comparisonAttribute == "version" and .[$i].conditions[].userCondition.comparisonValue.stringValue == "${{ github.event.release.tag_name }}") | $i + 1'`
          configcat flag-v2 targeting condition add user --flag-id 614140 -e 08dcf9bb-7e45-4853-8b0e-0129d6009a4e --rule-position $position --attribute platform --comparator containsAnyOf --comparison-value "macos:" --comparison-value "ios:"
