# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch

# Disabled for now
# on:
#   push:
#     branches:
#     - master
#   pull_request:
#     branches:
#     - master
on:
  push:
    # Publish semver tags as releases.
    tags:
      - '!dbg*'
      - '!*-dbg*'
      - '!*-fix*'
      - '*.*.*'

env:
  flutter_version: "3.x"
  java_version: "17.x"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: "Cache - Flutter"
        uses: actions/cache@v3
        env:
          flutter_linux_path: "/opt/hostedtoolcache/flutter"
          flutter_macos_path: "/Users/runner/hostedtoolcache/flutter"
        with:
          path: ${{ env.flutter_linux_path }}
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          # channel: beta

      - run: flutter pub get
      - run: dart format --line-length 100 --set-exit-if-changed .
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze .
      - run: flutter test

  release-windows-amd64:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: -h

    - name: Install
      run: |
        choco install flutter --version 3.22.2 -y

    - name: Build
      run: |
        Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
        refreshenv

        flutter clean
        flutter pub get
        dart run msix:build
        dart run msix:pack
